/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.techbuzz.jooq.tables.records;


import com.sivalabs.techbuzz.jooq.tables.Votes;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VotesRecord extends UpdatableRecordImpl<VotesRecord> implements Record6<Long, Long, Long, Integer, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.votes.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.votes.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.votes.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.votes.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.votes.post_id</code>.
     */
    public void setPostId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.votes.post_id</code>.
     */
    public Long getPostId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.votes.val</code>.
     */
    public void setVal(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.votes.val</code>.
     */
    public Integer getVal() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.votes.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.votes.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.votes.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.votes.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Integer, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Integer, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Votes.VOTES.ID;
    }

    @Override
    public Field<Long> field2() {
        return Votes.VOTES.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return Votes.VOTES.POST_ID;
    }

    @Override
    public Field<Integer> field4() {
        return Votes.VOTES.VAL;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Votes.VOTES.CREATED_AT;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Votes.VOTES.UPDATED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getPostId();
    }

    @Override
    public Integer component4() {
        return getVal();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getPostId();
    }

    @Override
    public Integer value4() {
        return getVal();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public VotesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VotesRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public VotesRecord value3(Long value) {
        setPostId(value);
        return this;
    }

    @Override
    public VotesRecord value4(Integer value) {
        setVal(value);
        return this;
    }

    @Override
    public VotesRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VotesRecord value6(LocalDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public VotesRecord values(Long value1, Long value2, Long value3, Integer value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VotesRecord
     */
    public VotesRecord() {
        super(Votes.VOTES);
    }

    /**
     * Create a detached, initialised VotesRecord
     */
    public VotesRecord(Long id, Long userId, Long postId, Integer val, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Votes.VOTES);

        setId(id);
        setUserId(userId);
        setPostId(postId);
        setVal(val);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
