/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.techbuzz.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqVotes implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long userId;
    private Long postId;
    private BigDecimal val;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public JooqVotes() {}

    public JooqVotes(JooqVotes value) {
        this.id = value.id;
        this.userId = value.userId;
        this.postId = value.postId;
        this.val = value.val;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public JooqVotes(
        Long id,
        Long userId,
        Long postId,
        BigDecimal val,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.userId = userId;
        this.postId = postId;
        this.val = val;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.votes.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.votes.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.votes.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.votes.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.votes.post_id</code>.
     */
    public Long getPostId() {
        return this.postId;
    }

    /**
     * Setter for <code>public.votes.post_id</code>.
     */
    public void setPostId(Long postId) {
        this.postId = postId;
    }

    /**
     * Getter for <code>public.votes.val</code>.
     */
    public BigDecimal getVal() {
        return this.val;
    }

    /**
     * Setter for <code>public.votes.val</code>.
     */
    public void setVal(BigDecimal val) {
        this.val = val;
    }

    /**
     * Getter for <code>public.votes.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.votes.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.votes.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.votes.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqVotes other = (JooqVotes) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.postId == null) {
            if (other.postId != null)
                return false;
        }
        else if (!this.postId.equals(other.postId))
            return false;
        if (this.val == null) {
            if (other.val != null)
                return false;
        }
        else if (!this.val.equals(other.val))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.postId == null) ? 0 : this.postId.hashCode());
        result = prime * result + ((this.val == null) ? 0 : this.val.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqVotes (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(postId);
        sb.append(", ").append(val);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
