/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.techbuzz.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JooqCategories implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String slug;
    private String description;
    private String image;
    private BigDecimal displayOrder;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public JooqCategories() {}

    public JooqCategories(JooqCategories value) {
        this.id = value.id;
        this.name = value.name;
        this.slug = value.slug;
        this.description = value.description;
        this.image = value.image;
        this.displayOrder = value.displayOrder;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public JooqCategories(
        Long id,
        String name,
        String slug,
        String description,
        String image,
        BigDecimal displayOrder,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.description = description;
        this.image = image;
        this.displayOrder = displayOrder;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.categories.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.categories.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.categories.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.categories.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.categories.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Setter for <code>public.categories.slug</code>.
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Getter for <code>public.categories.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.categories.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.categories.image</code>.
     */
    public String getImage() {
        return this.image;
    }

    /**
     * Setter for <code>public.categories.image</code>.
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * Getter for <code>public.categories.display_order</code>.
     */
    public BigDecimal getDisplayOrder() {
        return this.displayOrder;
    }

    /**
     * Setter for <code>public.categories.display_order</code>.
     */
    public void setDisplayOrder(BigDecimal displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * Getter for <code>public.categories.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.categories.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.categories.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.categories.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final JooqCategories other = (JooqCategories) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        }
        else if (!this.description.equals(other.description))
            return false;
        if (this.image == null) {
            if (other.image != null)
                return false;
        }
        else if (!this.image.equals(other.image))
            return false;
        if (this.displayOrder == null) {
            if (other.displayOrder != null)
                return false;
        }
        else if (!this.displayOrder.equals(other.displayOrder))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.image == null) ? 0 : this.image.hashCode());
        result = prime * result + ((this.displayOrder == null) ? 0 : this.displayOrder.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("JooqCategories (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(slug);
        sb.append(", ").append(description);
        sb.append(", ").append(image);
        sb.append(", ").append(displayOrder);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
