/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.techbuzz.jooq;


import com.sivalabs.techbuzz.jooq.tables.Categories;
import com.sivalabs.techbuzz.jooq.tables.Posts;
import com.sivalabs.techbuzz.jooq.tables.Users;
import com.sivalabs.techbuzz.jooq.tables.Votes;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.posts</code>.
     */
    public final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.votes</code>.
     */
    public final Votes VOTES = Votes.VOTES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.CATEGORY_ID_SEQ,
            Sequences.POST_ID_SEQ,
            Sequences.USER_ID_SEQ,
            Sequences.VOTE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categories.CATEGORIES,
            Posts.POSTS,
            Users.USERS,
            Votes.VOTES
        );
    }
}
