/*
 * This file is generated by jOOQ.
 */
package com.sivalabs.techbuzz.jooq;


import com.sivalabs.techbuzz.jooq.tables.Categories;
import com.sivalabs.techbuzz.jooq.tables.Posts;
import com.sivalabs.techbuzz.jooq.tables.Users;
import com.sivalabs.techbuzz.jooq.tables.Votes;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>public.posts</code>.
     */
    public static final Posts POSTS = Posts.POSTS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.votes</code>.
     */
    public static final Votes VOTES = Votes.VOTES;
}
